// This file was generated by package:dart_define, DO NOT modify or remove these comments
class Env {
  Env._();
  
  /// Keycloak API URL
  static const kcUrl = String.fromEnvironment('KC_URL');

  /// Keycloak realm name
  static const kcRealm = String.fromEnvironment('KC_REALM');

  /// Keycloak client ID
  static const kcClientId = String.fromEnvironment('KC_CLIENT_ID');

  /// App auth scheme for AppAuth redirect URI
  static const kcAppAuthScheme = String.fromEnvironment('KC_APP_AUTH_SCHEME');
}

    